import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import { addAccountReqDB } from "Database/addAccountReqDB";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

const index = (props) => {
  const [show, setShow] = useState(false);
  const [accounts, setAccounts] = useState(props.data?.data)
//   console.log('accounts', accounts)

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-10">
            <Topbar
              pageName={"Add Accounts "}
              color={"#7845E7"}
              show={show}
              setShow={setShow}
            />
            <div className="grid md:grid-cols-1 my-0 mx-4">
              <div className="md:flex block  items-center justify-between pr-10 mt-5">
                <Link
                  href={"/create-ad-account"}
                  className="bg-[#DBDEE4] md:text-[16px] text-[12px] font-bold border border-[#7A8489] rounded-xl px-[20px] py-[12px]"
                >
                  Crete Ad Account
                </Link>

                <div className="dropdown relative">
                  <button
                    id="dropdownMenuButton2"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                    className="bg-[#DBDEE4] flex items-center border border-[#7A8489] md:text-[16px] text-[12px] mt-3 md:mt-0 font-bold rounded-xl px-[20px] py-[12px]"
                  >
                    All Ad Account
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth={1.5}
                      stroke="currentColor"
                      className="w-5 h-5 ml-2"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M19.5 8.25l-7.5 7.5-7.5-7.5"
                      />
                    </svg>
                  </button>
                  <ul
                    className="dropdown-menu w-full absolute  bg-white text-base z-50 float-left py-2 list-none text-left rounded-lg shadow-lg mt-1 hidden m-0 bg-clip-padding border-none left-auto right-0
  "
                    aria-labelledby="dropdownMenuButton2"
                  >
                    <li className="dropdown-item text-sm py-2 px-4 font-semibold block w-full whitespace-nowrap bg-transparent text-gray-700  hover:bg-[#8FD59E] ">
                      Pending
                    </li>
                    <li className="dropdown-item text-sm py-2 px-4 font-semibold block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-[#8FD59E]">
                      Rejected
                    </li>
                    <li className="dropdown-item text-sm py-2 px-4 font-semibold block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-[#8FD59E]">
                      Need Review
                    </li>
                  </ul>
                </div>
              </div>

              <div className="overflow-x-auto">
                <table className="table-auto w-full  mt-10 ">
                  <thead className="text-white">
                    <tr className="text-black flex md:flex-row flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0">
                      <th className="p-3 text-left text-[#717D82]">Date</th>
                      <th className="p-3 text-left text-[#717D82]">
                        Add Account Name
                      </th>
                      <th className="p-3 text-left text-[#717D82]">
                        Add Account Number
                      </th>
                      <th className="p-3 text-left text-[#717D82]">
                        Page Name
                      </th>
                      <th className="p-3 text-left text-[#717D82]">Page ID</th>

                      <th className="p-3 text-left text-[#717D82]">Action</th>
                    </tr>
                  </thead>

                  {accounts.map((ad, i) => {
                    return (
                      <tbody key={i}>
                        <TableRow ad={ad} />
                      </tbody>
                    );
                  })}
                </table>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export async function getServerSideProps(context) {
  const res = await fetch(`https://boosterbd-server.onrender.com/api/v1/ad-account`);
  const data = await res.json();
  return {
    props: {data}, // will be passed to the page component as props
  };
}

export default index;

const TableRow = ({ ad }) => {
  const { createdAt, addAccountName, addAccountNumber, pageName, pageID, country } =
    ad;
  return (
    <>
      <tr className="flex md:flex-row flex-no wrap sm:table-row mb-2 sm:mb-0 text-[14px]">
        <td className="text-[#464F53] p-3">{createdAt.slice(0, 10)}</td>
        <td className="text-[#464F53] p-3 truncate">{addAccountName}</td>
        <td className="text-[#464F53] p-3 ">{addAccountNumber}</td>
        <td className="text-[#464F53] p-3 ">{pageName}</td>
        <td className="text-[#464F53] p-3 ">{pageID}</td>
        <td className="   p-3  cursor-pointer">
          <button className="font-semibold bg-[#26C536] px-4 py-2 sm:my-1 rounded-md text-[12px] text-white">
            Active
          </button>
          <button className="font-semibold bg-[#FC544B] mx-2 px-4 py-2 sm:my-1 rounded-md text-[12px] text-white">
            Rejected
          </button>
          <button className="font-semibold bg-[#8756EF] px-4 py-2 sm:my-1 rounded-md text-[12px] text-white">
            Pending
          </button>
        </td>
      </tr>
    </>
  );
};
