import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import Head from "next/head";
import React, { useState } from "react";
import { useForm } from "react-hook-form";

const index = () => {
  const [show, setShow] = useState(false);
  const charge = 100;
  const [limitAmount, setLimitAmount] = useState();
  const {
    register,
    handleSubmit,
    reset,
    watch,
    formState: { errors },
  } = useForm();
  const onSubmit = async (data) => {
    console.log("data", data);
    if (data.limitAdAccountName === "selectAccount") {
      return;
    }
    console.log('data.limitAdAccountName', data.limitAdAccountName)
    setLimitAmount(data.rechargeAmount);
  };

  console.log("limitAmount", limitAmount);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-10">
            <Topbar pageName={"Limit Request"} show={show} setShow={setShow} />

            <div className="grid md:grid-cols-3 gap-6 mx-8 my-6 mr-8 ">
              <div className=" bg-gray-400 shadow-lg w-full rounded p-4">
                <h3>
                  <strong>Notice:</strong> আমরা সরাসরি লিমিট বাড়াতে পারি না।
                  আমাদের জন্যে ফেসবুকের প্রতিনিধি নিয়োগ দেয়া আছে। আমরা উনাদেরকে
                  ইমেইল করার পরে, উনারা পেমেন্ট চেক করে লিমিট আপডেট করে দেন। তাই
                  যাদের লিমিট রিকুয়েস্ট দরকার, তারা সর্বদা হাতে ১০০$-২০০$ ডলার
                  রেখে ব্যালান্স রিকুয়েস্ট দিন।{" "}
                </h3>
              </div>

              {/* form */}
              <div className="col-span-2 bg-gray-400 shadow-lg w-full rounded p-4">
                <form onSubmit={handleSubmit(onSubmit)}>
                  {/* limitAdAccountName */}
                  <div className="flex justify-center">
                    <div className="relative mb-3 xl:w-full">
                      <select
                        type="text"
                        className="peer m-0 block h-[58px] w-full rounded border border-solid border-neutral-300 bg-[#f7f7f7] bg-clip-padding py-4 px-3 text-base font-normal leading-tight text-neutral-700 ease-in-out placeholder:text-transparent focus:border-primary focus:bg-white focus:pt-[1.625rem] focus:pb-[0.625rem] focus:text-neutral-700 focus:shadow-te-primary focus:outline-none  dark:text-[#f7f7f7] [&:not(:placeholder-shown)]:pt-[1.625rem] [&:not(:placeholder-shown)]:pb-[0.625rem]"
                        {...register("limitAdAccountName", {
                          required: {
                            value: true,
                            message: "Account Name is required",
                          },
                        })}
                      >
                        <option defaultValue="selectAccount">
                          Please Select Your Account
                        </option>
                        <option value="female">female</option>
                        <option value="male">male</option>
                        <option value="other">other</option>
                      </select>
                      <label className="pointer-events-none absolute top-0 left-0 origin-[0_0] border border-solid border-transparent py-4 px-3 text-neutral-900 transition-[opacity,_transform] duration-100 ease-in-out peer-focus:translate-x-[0.15rem] peer-focus:-translate-y-2 peer-focus:scale-[0.85] peer-focus:opacity-[0.65] peer-[:not(:placeholder-shown)]:translate-x-[0.15rem] peer-[:not(:placeholder-shown)]:-translate-y-2 peer-[:not(:placeholder-shown)]:scale-[0.85] peer-[:not(:placeholder-shown)]:opacity-[0.65] motion-reduce:transition-none dark:text-neutral-900">
                        Ad Account Name
                      </label>
                      <small className="text-[#FF4B2B] custom_font custom_font_size">
                        {errors?.limitAdAccountName?.message}
                      </small>
                    </div>
                  </div>

                  {/* rechargeAmount */}
                  <div className="flex justify-center">
                    <div className="relative mb-3 xl:w-full">
                      <input
                        type="text"
                        className="peer m-0 block h-[58px] w-full rounded border border-solid border-neutral-300 bg-[#f7f7f7] bg-clip-padding py-4 px-3 text-base font-normal leading-tight text-neutral-700 ease-in-out placeholder:text-transparent focus:border-primary focus:bg-white focus:pt-[1.625rem] focus:pb-[0.625rem] focus:text-neutral-700 focus:shadow-te-primary focus:outline-none  dark:text-[#f7f7f7] [&:not(:placeholder-shown)]:pt-[1.625rem] [&:not(:placeholder-shown)]:pb-[0.625rem]"
                        {...register("rechargeAmount", {
                          required: {
                            value: true,
                            message: "Please provide your amount",
                          },
                          pattern: {
                            value:
                              /^(?!(?:^[-+]?[0.]+(?:[Ee]|$)))(?!(?:^-))(?:(?:[+-]?)(?=[0123456789.])(?:(?:(?:[0123456789]+)(?:(?:[.])(?:[0123456789]*))?|(?:(?:[.])(?:[0123456789]+))))(?:(?:[Ee])(?:(?:[+-]?)(?:[0123456789]+))|))$/,
                            message: "Please provide a valid amount",
                          },
                        })}
                      />
                      <label className="pointer-events-none absolute top-0 left-0 origin-[0_0] border border-solid border-transparent py-4 px-3 text-neutral-900 transition-[opacity,_transform] duration-100 ease-in-out peer-focus:translate-x-[0.15rem] peer-focus:-translate-y-2 peer-focus:scale-[0.85] peer-focus:opacity-[0.65] peer-[:not(:placeholder-shown)]:translate-x-[0.15rem] peer-[:not(:placeholder-shown)]:-translate-y-2 peer-[:not(:placeholder-shown)]:scale-[0.85] peer-[:not(:placeholder-shown)]:opacity-[0.65] motion-reduce:transition-none dark:text-neutral-900">
                        Recharge Your Amount
                      </label>
                      <small className="text-[#FF4B2B] custom_font custom_font_size">
                        {errors?.rechargeAmount?.message}
                      </small>
                    </div>
                  </div>

                  <input
                    type="submit"
                    value="SEND REQUEST"
                    className="inline-block rounded-l bg-primary px-12 py-2 rounded shadow-[#8756ef] text-semibold  uppercase leading-normal text-white transition duration-150 ease-in-out bg-[#8756ef] cursor-pointer hover:bg-[#fff] hover:text-[#8756ef] "
                  />
                </form>
              </div>
              {/* <div>3</div> */}
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

const Review = () => {
  return (
    <>
      {/* <!-- Button trigger modal --> */}
      <button
        type="button"
        class="inline-block rounded bg-primary px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
        data-te-toggle="modal"
        data-te-target="#exampleModal"
        data-te-ripple-init
        data-te-ripple-color="light"
      >
        Launch demo modal
      </button>

      {/* <!-- Modal --> */}
      <div
        data-te-modal-init
        class="fixed top-0 left-0 z-[1055] hidden h-full w-full overflow-y-auto overflow-x-hidden outline-none"
        id="exampleModal"
        tabindex="-1"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true"
      >
        <div
          data-te-modal-dialog-ref
          class="pointer-events-none relative w-auto translate-y-[-50px] opacity-0 transition-all duration-300 ease-in-out min-[576px]:mx-auto min-[576px]:mt-7 min-[576px]:max-w-[500px]"
        >
          <div class="min-[576px]:shadow-[0_0.5rem_1rem_rgba(#000, 0.15)] pointer-events-auto relative flex w-full flex-col rounded-md border-none bg-white bg-clip-padding text-current shadow-lg outline-none dark:bg-neutral-600">
            <div class="flex flex-shrink-0 items-center justify-between rounded-t-md border-b-2 border-neutral-100 border-opacity-100 p-4 dark:border-opacity-50">
              <h5
                class="text-xl font-medium leading-normal text-neutral-800 dark:text-neutral-200"
                id="exampleModalLabel"
              >
                Modal title
              </h5>
              <button
                type="button"
                class="box-content rounded-none border-none hover:no-underline hover:opacity-75 focus:opacity-100 focus:shadow-none focus:outline-none"
                data-te-modal-dismiss
                aria-label="Close"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  class="h-6 w-6"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M6 18L18 6M6 6l12 12"
                  />
                </svg>
              </button>
            </div>
            <div class="relative flex-auto p-4" data-te-modal-body-ref>
              Modal body text goes here.
            </div>
            <div class="flex flex-shrink-0 flex-wrap items-center justify-end rounded-b-md border-t-2 border-neutral-100 border-opacity-100 p-4 dark:border-opacity-50">
              <button
                type="button"
                class="inline-block rounded bg-primary-100 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-primary-700 transition duration-150 ease-in-out hover:bg-primary-accent-100 focus:bg-primary-accent-100 focus:outline-none focus:ring-0 active:bg-primary-accent-200"
                data-te-modal-dismiss
                data-te-ripple-init
                data-te-ripple-color="light"
              >
                Close
              </button>
              <button
                type="button"
                class="ml-1 inline-block rounded bg-primary px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
                data-te-ripple-init
                data-te-ripple-color="light"
              >
                Save changes
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default index;
