import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import Head from "next/head";
import Link from "next/link";
import React, { useState } from "react";

const index = () => {
  const [show, setShow] = useState(false);
  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-10">
            <Topbar pageName={"Setting"} show={show} setShow={setShow} />

            <div className="grid md:grid-cols-4 gap-4">
              <div className="p-6">
                <Link href={"/currency"} className="text-3xl">
                  Are You Looking For Currency?
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/add-account"} className="text-3xl">
                  Are You Looking For Add Account?
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/users/profile/abc"} className="text-3xl">
                  Profile
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/users"} className="text-3xl">
                  Manage Users
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/users/manage"} className="text-3xl">
                  Manage Users Roles
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/users/add-account"} className="text-3xl">
                  Add Account Requests
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/users/limit-update"} className="text-3xl">
                  Limit Update
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/transactions"} className="text-3xl">
                  transactions
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/bill-management"} className="text-3xl">
                  Bill Management
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/review-management"} className="text-3xl">
                  Review Management
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/service"} className="text-3xl">
                  Service
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/create-ad-account"} className="text-3xl">
                  Create ad accounts
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/ad-account-requests"} className="text-3xl">
                  ad accounts requests
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/top-up"} className="text-3xl">
                  top up
                </Link>
              </div>
              <div className="p-6">
                <Link href={"/ad-limit-request"} className="text-3xl">
                  ad limit request
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default index;
