import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import Head from "next/head";
import React, { useState } from "react";
import { useForm } from "react-hook-form";

const index = () => {
  const [show, setShow] = useState("false");

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm();
  const onSubmit = (data) => console.log(data);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-10">
            <Topbar pageName={"Top-up"} show={show} setShow={setShow} />

            <section className="grid md:grid-cols-1 gap-4 m-6">
              <h3 className="text-xl font-semibold">Current Balance $39.25</h3>
              <h3 className="text-xl font-semibold text-[#8756ef]">
                Pending Balance $39.25
              </h3>

              <div className="flex justify-between w-96">
                <h3 className="text-xl font-semibold">Payment Method</h3>
                <div className="">
                  <input type="checkbox" className="checkbox-round" />
                  <label className="ml-4 font-semibold text-[#7A8489]">
                    Cash
                  </label>
                </div>
              </div>

              {/* amount to add */}
              <div className="grid md:grid-cols-3 gap-4 w-full">
                <div className="text-left my-auto">
                  <h3 className="text-md font-semibold text-[#7A8489]">
                    Amount to Add
                  </h3>
                </div>
                <div className="text-left ">
                  <input
                    type="text"
                    placeholder="20,000"
                    className="w-full peer block min-h-[auto]  rounded border bg-transparent py-[0.32rem] px-3 leading-[1.6] outline-none transition-all duration-200 ease-linear   motion-reduce:transition-none dark:text-neutral-700 "
                  />
                </div>
                <div className="text-left "></div>
              </div>

              {/* paid to */}
              <div className="grid md:grid-cols-3 gap-4 w-full my-4">
                <div className="text-left my-auto">
                  <h3 className="text-md font-semibold text-[#7A8489]">
                    Paid to
                  </h3>
                </div>
                <div className="text-left ">
                  <input type="checkbox" className="checkbox-round" />
                  <label className="ml-4 font-md text-[#7A8489]">Noman</label>
                  <input type="checkbox" className="checkbox-round ml-4" />
                  <label className="ml-4 font-md text-[#7A8489]">Asif</label>
                  <input type="checkbox" className="checkbox-round ml-4" />
                  <label className="ml-4 font-md text-[#7A8489]">Akbar</label>
                </div>
                <div className="text-left "></div>
              </div>

              {/* confirm */}

              <div className="grid md:grid-cols-3 gap-4 w-full my-4">
                <div className="text-left my-auto"></div>
                <div className="text-left ">
                  <input
                    type="submit"
                    value="Confirm"
                    className="text-white px-10 py-2 rounded bg-[#47C363] text-semibold"
                  />
                  <div className="bg-[#D9D9D9] text-[#8756EF] font-semibold text-md p-4 rounded shadow-lg my-4">
                    <h4>
                      Thank You for your payment. We will notify you after
                      verification
                    </h4>
                  </div>
                </div>
                <div className="text-left "></div>
              </div>

              {/* mobile banking */}
              <div className="grid md:grid-cols-3 gap-4 w-full my-4">
                <div className="text-left my-auto"></div>
                <div className="text-left ">
                  <input type="checkbox" className="checkbox-round" />
                  <label className="ml-4 font-semibold ">Mobile Banking</label>

                  <div className="grid md:grid-cols-3 gap-4 my-6">
                    <div>
                      <input type="checkbox" className="checkbox-round" />
                      <label className="ml-4 font-semibold ">Nagad</label>
                    </div>
                    <div>
                      <input type="checkbox" className="checkbox-round" />
                      <label className="ml-4 font-semibold ">bKash</label>
                    </div>
                    <div>
                      <input type="checkbox" className="checkbox-round" />
                      <label className="ml-4 font-semibold ">Rocket</label>
                    </div>
                    <div>
                      <input type="checkbox" className="checkbox-round" />
                      <label className="ml-4 font-semibold ">Upay</label>
                    </div>
                    <div>
                      <input type="checkbox" className="checkbox-round" />
                      <label className="ml-4 font-semibold ">mCash</label>
                    </div>
                    <div>
                      <input type="checkbox" className="checkbox-round" />
                      <label className="ml-4 font-semibold ">sureCash</label>
                    </div>
                  </div>
                </div>

                <div className="text-left "></div>
              </div>

              {/* amount to add */}
              <div className="grid md:grid-cols-3 gap-4 w-full">
                <div className="text-left my-auto">
                  <h3 className="text-md font-semibold text-[#7A8489]">
                    Amount to Add
                  </h3>
                </div>
                <div className="text-left ">
                  <input
                    type="text"
                    placeholder="20,000"
                    className="w-full peer block min-h-[auto]  rounded border bg-transparent py-[0.32rem] px-3 leading-[1.6] outline-none transition-all duration-200 ease-linear   motion-reduce:transition-none dark:text-neutral-700 "
                  />
                </div>
                <div className="text-left "></div>
              </div>

              {/* customer phone number*/}
              <div className="grid md:grid-cols-3 gap-4 w-full">
                <div className="text-left my-auto">
                  <h3 className="text-md font-semibold text-[#7A8489]">
                    Customer Phone Number
                  </h3>
                </div>
                <div className="text-left ">
                  <input
                    type="text"
                    placeholder="+8801734165283"
                    className="w-full peer block min-h-[auto]  rounded border bg-transparent py-[0.32rem] px-3 leading-[1.6] outline-none transition-all duration-200 ease-linear   motion-reduce:transition-none dark:text-neutral-700 "
                  />
                </div>
                <div className="text-left "></div>
              </div>

              {/* Paid To*/}
              <div className="grid md:grid-cols-3 gap-4 w-full">
                <div className="text-left my-auto">
                  <h3 className="text-md font-semibold text-[#7A8489]">
                    Paid to
                  </h3>
                </div>
                <div className="text-left ">
                  <select
                    type="text"
                    placeholder="+8801734165283"
                    className="w-full peer block min-h-[auto]  rounded border bg-transparent py-[0.32rem] px-3 leading-[1.6] outline-none transition-all duration-200 ease-linear   motion-reduce:transition-none dark:text-neutral-700 "
                  >
                    <option value="Please Select">Please Select</option>
                    <option value="+880123622333">+880123 622 333</option>
                    <option value="+880123622333">+880123 622 333</option>
                  </select>
                </div>
                <div className="text-left "></div>
              </div>

              {/* transaction id*/}
              <div className="grid md:grid-cols-3 gap-4 w-full">
                <div className="text-left my-auto">
                  <h3 className="text-md font-semibold text-[#7A8489]">
                    Transaction ID
                  </h3>
                </div>
                <div className="text-left ">
                  <div className="grid md:grid-cols-2 gap-4">
                    <div>
                      <input
                        type="text"
                        placeholder="Transaction ID"
                        className="w-full peer block min-h-[auto]  rounded border bg-transparent py-[0.32rem] px-3 leading-[1.6] outline-none transition-all duration-200 ease-linear   motion-reduce:transition-none dark:text-neutral-700 "
                      />
                    </div>
                    
                    <div><input
                    type="file"
                    placeholder="Attach File"
                    className="w-full peer block min-h-[auto]  rounded border bg-transparent py-[0.32rem] px-3 leading-[1.6] outline-none transition-all duration-200 ease-linear   motion-reduce:transition-none dark:text-neutral-700 "
                  /></div>
                  </div>
                </div>
                <div className="text-left "></div>
              </div>

              {/* confirm */}

              <div className="grid md:grid-cols-3 gap-4 w-full my-4">
                <div className="text-left my-auto"></div>
                <div className="text-left ">
                  <input
                    type="submit"
                    value="Confirm"
                    className="text-white px-10 py-2 rounded bg-[#47C363] text-semibold"
                  />
                  <div className="bg-[#D9D9D9] text-[#8756EF] font-semibold text-md p-4 rounded shadow-lg my-4">
                    <h4>
                      Thank You for your payment. We will notify you after
                      verification
                    </h4>
                  </div>
                </div>
                <div className="text-left "></div>
              </div>




            </section>
          </div>
        </section>
      </main>
    </>
  );
};

export default index;
